### ISSUE TITLE
Error problem

### ISSUE THREAD

**Issue by fturiot** [fiznool/express-mongo-sanitize#104]
Hi, 
I have this probleme when i use 
Cannot set property headers of #<Http2ServerRequest> which has only a getter

i use http2-express-bridge' with express , it's ok with helme core, xss clean, express-rate-limit but not here
thanks for help 
regards

**Comment by fiznool** [comment]
Hi, if you could provide a sample repo so I can reproduce, I'd be happy to look at this. Please reopen if you can do so.
