### ISSUE TITLE
Logical Bypass

### ISSUE THREAD

**Issue by posix-lee** [fiznool/express-mongo-sanitize#18]
sanitizing of express-mongo-sanitize module is not enough
can be bypassed:

```js
sanitize('"a\'"||1}//${}', {replaceWith:'_'}); // "a'"||1}//${}
```

**Comment by fiznool** [comment]
Could you elaborate on the attack vector that the code sample introduces?

As described in the readme:

> This module searches for any keys in objects that begin with a $ sign or contain a .

**Comment by fiznool** [comment]
I'm still unsure on the attack vector that this introduces. Please feel free to email me with more details and I can look into it, otherwise I'll close this out for now.
