### ISSUE TITLE
Node REPL produces false value for `obj instanceof Object`

### ISSUE THREAD

**Issue by pedrovagner** [fiznool/express-mongo-sanitize#3]
An `Object` literal passed through Node REPL isn't equal to the module context. That is, an `obj` passed though Node REPL produces false into this line of code `obj instanceof Object`. I find out this after 2 hours stuck into this. To know more about see: [In REPL, required modules have different Object than command-line](https://github.com/nodejs/node-v0.x-archive/issues/1482)

Please, change `obj instanceof Object` to `typeof obj === 'object' && obj !== null`. Thanks.

**Comment by fiznool** [comment]
Thanks for the issue report. Could you provide a code snippet which reproduces the issue?

**Comment by fiznool** [comment]
I've just published v1.3.1 to npm which includes a more robust check for an object, inspired by your code snippet above. Can you check if the issue still exists with this version?

**Comment by pedrovagner** [comment]
Your commit doesn't solved this issue, I'm still having false negative errors. I just made a PR that fix it. Is necessary a more robust solution to check for `isPlainObject` function?

**Comment by fiznool** [comment]
Thanks, fixed and published as v1.3.2.
