### ISSUE TITLE
Add SECURITY.md?

### ISSUE THREAD

**Issue by azu** [fiznool/express-mongo-sanitize#33]
Hi!
Can you add `SECURITY.md` to this repository?
It will help us to report a security issue.

- [Adding a security policy to your repository - GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository)

I found a security issue and report it to @fiznool [email](https://github.com/fiznool/express-mongo-sanitize/blob/ecc1cd02d4e665d07ab12032d4aaa2e2335b0adc/package.json#L25).

For more details, please check the email titled `express-mongo-sanitize security issue`.

**Comment by fiznool** [comment]
Thank you for bringing this to my attention. I will look to get this sorted ASAP.

**Comment by fiznool** [comment]
Thanks again, a security policy has now been added.
