### ISSUE TITLE
Using regex to find the issue before recursively trying to fix it

### ISSUE THREAD

**Issue by gtmsingh** [fiznool/express-mongo-sanitize#75]
**Proposal:**
Can we use simple regex like `"\$[\w \.]+\":` on JSONified object to identify if there are any key which has security concern. This could potentially increase the overall performance of the library.

Before I go ahead with it, I needed some feedback about it. Is it a good idea?

Major concern that I have with this approach is: [ReDDoS](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS)

**Comment by fiznool** [comment]
I'm a little wary of changing things for theoretical purposes. Is there a particular performance issue you are experiencing with the current implementation?

**Comment by gtmsingh** [comment]
No not at all really.
