### ISSUE TITLE
Option for retrieve the body before sanitized

### ISSUE THREAD

**Issue by goffjira** [fiznool/express-mongo-sanitize#78]
Hi Fiznool, Are there any options available for retrieve the req.body before it got sanitized, My use-case is that I want to log the shape of data that malicious user try to perform on my site, I have tried the option: dryRun:true though and I can access the version before the payload(req.body) being cleaned which is great, however with that DryRun, the whole sanitization proces is cancelled an what I receive at the route middleware function is look the same as when you request it on postman. Any help?

**Comment by fiznool** [comment]
Maybe another piece of middleware higher up in the chain? For example:

``` js
const express = require('express');
const bodyParser = require('body-parser');
const mongoSanitize = require('express-mongo-sanitize');

const app = express();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use((req, res, next) => {
  console.log(res.body);
  next();
});


app.use(mongoSanitize());
```
